language: php
php:
  - 5.3
before_install:
- pear install pear/PHP_CodeSniffer
- phpenv rehash
- composer global require drush/drush:6.*
- sudo ln -s $HOME/.composer/vendor/bin/drush /usr/local/bin/drush
- drush --version
- drush dl coder --destination=$HOME/.drush
- ln -s $TRAVIS_BUILD_DIR $HOME/.drush/rebuild
- cd $HOME/.drush/rebuild
- composer install
- drush cache-clear drush
script:
- drush drupalcs rebuild.drush.inc
- drush drupalcs includes
- drush drupalcs tests
- phpunit --bootstrap=$HOME/composer/vendor/drush/drush/tests/drush_testcase.inc $HOME/.drush/rebuild/tests/rebuildTest.php
