language: php
php:
  - 5.3
before_install:
- echo 'export PATH=$HOME/.composer/vendor/bin:$PATH' >> $HOME/.bashrc
- cat $HOME/.bashrc
- ls $HOME
- source /home/travis/.bashrc
- composer global require drush/drush:6.*
- sudo ln -s $HOME/.composer/vendor/bin/drush /usr/local/bin/drush
- drush --version
- drush dl coder --destination=$HOME/.drush
- mv $HOME/rebuild $HOME/.drush/
- cd $HOME/.drush/rebuild
- composer install
- drush cache-clear drush
script:
- drush drupalcs rebuild.drush.inc
- drush drupalcs includes
- drush drupalcs tests
- phpunit --bootstrap=/home/travis/drush/tests/drush_testcase.inc /home/travis/.drush/rebuild/tests/rebuildTest.php
