language: php
php:
  - 5.3
before_install:
- pear channel-discover pear.drush.org
- pear install drush/drush-5.8.0
- pear install pear/PHP_CodeSniffer
- phpenv rehash
- drush dl coder --destination=/home/travis/.drush
- drush dl composer-8.x-1.0-alpha5 --destination=/home/travis/.drush
- drush cache-clear drush
- cd ..
- mv rebuild /home/travis/.drush/
- wget http://ftp.drupal.org/files/projects/drush-7.x-5.8.tar.gz
- tar -zxvf drush-7.x-5.8.tar.gz
- mv drush /home/travis/
- cd /home/travis/.drush/rebuild
- drush composer install
before_script:
- cd /home/travis/.drush/rebuild
script:
- drush drupalcs rebuild.drush.inc
- drush drupalcs includes
- drush drupalcs tests
- phpunit --bootstrap=/home/travis/drush/tests/drush_testcase.inc /home/travis/.drush/rebuild/tests/rebuildTest.php
