language: php
php:
  - 5.3
before_install:
- pear channel-discover pear.drush.org
- pear install drush/drush-5.0.0
env:
  - DRUSH_DIRNAME=dirname -- `which drush`
script: phpunit --bootstrap="$DRUSH_DIRNAME/tests/drush_testcase.inc"
